resolver: lts-12.14

ghc-build: alpine

extra-deps:
- filepath-1.4.2.1
- filemanip-0.3.6.3
- directory-1.3.3.2
- process-1.6.5.1

packages:
- 'src'
- 'src/src/fix-agda-whitespace'
- 'src/src/size-solver'
