resolver: lts-12.14

ghc-build: alpine

extra-deps:
- filepath-1.4.2.1
- filemanip-0.3.6.3

# Local packages, usually specified by relative directory name
packages:
- 'src'
- 'src/src/fix-agda-whitespace'
- 'src/src/size-solver'
